-- ATV 1
CREATE PROCEDURE incluir_clientes
    @RG VARCHAR(9),
    @NOME VARCHAR(50),
    @ENDERECO VARCHAR(50),
    @BAIRRO VARCHAR(30),
    @CIDADE VARCHAR(30), 
    @ESTADO CHAR(2),
    @TELEFONE VARCHAR(15),
    @EMAIL VARCHAR(30),
    @DATANASCIMENTO DATETIME,
    @Sexo CHAR(1)
AS
BEGIN
    INSERT INTO dbo.CLIENTES
    (
        RG, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO,
        TELEFONE, EMAIL, DATANASCIMENTO, Sexo
    )
    VALUES
    (
        @RG, @NOME, @ENDERECO, @BAIRRO, @CIDADE, @ESTADO,
        @TELEFONE, @EMAIL, @DATANASCIMENTO, @Sexo
    )
END
GO

create procedure Selecionar_clientes (@ID float)
as
begin 
select * FROM CLIENTES WHERE COD_CLIENTE = @ID
end

GO

create procedure Alterar_Cliente
	@RG VARCHAR(9),
	@NOME VARCHAR(50),
	@ENDERECO VARCHAR(50),
	@BAIRRO VARCHAR(30),
	@CIDADE VARCHAR(30), 
	@ESTADO CHAR(2),
	@TELEFONE VARCHAR(15),
	@EMAIL VARCHAR(30),
	@DATANASCIMENTO DATETIME,
	@Sexo char(1),
	@COD_CLIENTE int
as
begin
		update dbo.CLIENTES
		set

		RG = @RG,
		NOME = @NOME,
		ENDERECO = @ENDERECO,
		BAIRRO = @BAIRRO,
		CIDADE = @CIDADE,
		ESTADO = @ESTADO,
		TELEFONE = @TELEFONE, 
		EMAIL = @EMAIL, 
		DATANASCIMENTO = CONVERT(VARCHAR,@DATANASCIMENTO,102),
		SEXO = @Sexo
		where COD_CLIENTE = @COD_CLIENTE
end

GO
create procedure Excluir_clientes (@ID float)
as
	begin 
		DELETE FROM LOCACOES WHERE COD_CLIENTE = @ID
		DELETE FROM CLIENTES WHERE COD_CLIENTE = @ID
end

EXEC incluir_clientes
'890635147', 
'João Pedro Costa Silva', 
'Rua beija-flor 149', 
'Alumínio', 
'Sorocaba', 
'PA',
'(34)3737279648',
'Joaocacetinho3@gmail.com', 
'2007-11-23', 
'M'
execute Selecionar_clientes 12
execute alterar_cliente @COD_CLIENTE = 5, @RG =  '890607387',@NOME =  'Juliano Teixeira dos Santos',
 @ENDERECO = 'Rua aninha garibaldi 376',@BAIRRO = 'Alúminio', @CIDADE =  'Sorocaba',@ESTADO =  'PA',
@TELEFONE = '3437372763831',@EMAIL = 'Joaocacetinho3@gmail.com',@DATANASCIMENTO = '2007-11-23',@Sexo = 'M'
execute Excluir_clientes 11

GO

--ATV 2
CREATE PROCEDURE Aniversariantes (@MES INT)
AS
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM CLIENTES 
        WHERE MONTH(DATANASCIMENTO) = @MES
    )
    BEGIN
        SELECT 
            NOME,
            DAY(DATANASCIMENTO) AS DIA_ANIVERSARIO
        FROM CLIENTES
        WHERE MONTH(DATANASCIMENTO) = @MES
        ORDER BY DAY(DATANASCIMENTO)
    END
    ELSE
    BEGIN
        PRINT 'Sem aniversariantes neste mês.'
    END
END

execute Aniversariantes 11

GO

-- ATV 3
CREATE PROCEDURE Resumo_aniversariantes
AS
BEGIN
    SELECT 
        M.MES,
        COUNT(DATANASCIMENTO) AS TOTAL_ANIVERSARIANTES
    FROM (
        SELECT 1 AS MES UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
        UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8
        UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12
    ) M
    LEFT JOIN CLIENTES C 
        ON MONTH(C.DATANASCIMENTO) = M.MES
    GROUP BY M.MES
    ORDER BY M.MES
END

execute Resumo_aniversariantes

GO

-- ATV 4
CREATE PROCEDURE CLIENTES_POR_CIDADE_IDADE
    @CIDADE VARCHAR(30),
    @IDADE_MAX INT
AS
BEGIN
    SELECT 
        NOME AS [Nome do Cliente],
        DATANASCIMENTO AS [Data Nascimento],
        DATEDIFF(YEAR, DATANASCIMENTO, GETDATE()) 
- CASE 
    WHEN DATEADD(YEAR, DATEDIFF(YEAR, DATANASCIMENTO, GETDATE()), DATANASCIMENTO) > GETDATE() 
    THEN 1 ELSE 0
  END as [idade]
    FROM CLIENTES
    WHERE 
        CIDADE = @CIDADE
        AND DATEDIFF(YEAR, DATANASCIMENTO, GETDATE()) <= @IDADE_MAX
END

execute CLIENTES_POR_CIDADE_IDADE 'Sorocaba', 60

go

-- ATV 5
CREATE PROCEDURE INCLUIR_LOCACAO
    @ID_CLIENTE NUMERIC(18,0),
    @ID_FILME NUMERIC(18,0)
AS
BEGIN
    DECLARE @DATA_LOCACAO DATETIME = GETDATE()

    INSERT INTO LOCACOES (COD_CLIENTE, COD_FILME, DATA_LOCACAO)
    VALUES (@ID_CLIENTE, @ID_FILME, @DATA_LOCACAO)

    UPDATE FILME
    SET STATUS = 'Alugado', RESERVADA = 's'
    WHERE COD_FILME = @ID_FILME

	select STATUS from FILME 
END

execute INCLUIR_LOCACAO 6, 7

go

--ATV 6
CREATE PROCEDURE DEVOLVER_FILME
    @ID_LOCACAO NUMERIC(18,0)
AS
BEGIN
    DECLARE @ID_FILME NUMERIC(18,0)

    SELECT @ID_FILME = COD_FILME
    FROM LOCACOES
    WHERE COD_LOCACAO = @ID_LOCACAO

    UPDATE LOCACOES
    SET DATA_DEVOLUCAO = GETDATE()
    WHERE COD_LOCACAO = @ID_LOCACAO

    UPDATE FILME
    SET STATUS = 'Disponivel'
    WHERE COD_FILME = @ID_FILME

	select COD_FILME, FILME, VALOR_LOCACAO, STATUS from FILME
END

execute DEVOLVER_FILME 18
